background = #1E1E2E
background-opacity = 0.90
foreground = #CDD6F4
cursor-color = #CDD6F4
selection-background = #45475A
selection-foreground = #CDD6F4

palette = 0=#313244
palette = 1=#F38BA8
palette = 2=#A6E3A1
palette = 3=#FAB387
palette = 4=#89B4FA
palette = 5=#CBA6F7
palette = 6=#89DCEB
palette = 7=#CDD6F4
palette = 8=#585B70
palette = 9=#FF8EAB
palette = 10=#B7F0B2
palette = 11=#FBE8BA
palette = 12=#A6C8FF
palette = 13=#DFB8FF
palette = 14=#A6EDFB
palette = 15=#FFFFFF
