foreground            #CDD6F4
background            #1E1E2E
background_opacity    0.90
selection_foreground  #CDD6F4
selection_background  #45475A

cursor                #CDD6F4
cursor_text_color     #1E1E2E

active_border_color   #CBA6F7
active_tab_background #CBA6F7

color0  #313244
color8  #585B70
color1  #F38BA8
color9  #FF8EAB
color2  #A6E3A1
color10 #B7F0B2
color3  #FAB387
color11 #FBE8BA
color4  #89B4FA
color12 #A6C8FF
color5  #CBA6F7
color13 #DFB8FF
color6  #89DCEB
color14 #A6EDFB
color7  #CDD6F4
color15 #FFFFFF
